"""
ICS calendar proxy — core fetch and rewrite logic.

Workflow:
  1. Fetch the upstream .ics URL.
  2. Parse into an icalendar.Calendar object.
  3. Collect every VTIMEZONE component and translate Windows TZID → IANA.
  4. Replace the original VTIMEZONE blocks with authoritative definitions
     generated by icalendar.Timezone.from_tzid() (RFC 5545 compliant,
     backed by the system IANA tzdata — no extra dependency needed).
  5. Rewrite every TZID parameter that appears on DTSTART / DTEND / DUE /
     RECURRENCE-ID / EXDATE / RDATE in VEVENT / VTODO / VJOURNAL.
  6. Return the serialised calendar bytes.
"""

from __future__ import annotations

import logging
from typing import Optional

import requests
from icalendar import Calendar, Timezone

from .timezones import WINDOWS_TO_IANA

logger = logging.getLogger(__name__)

# Properties on event/todo/journal components that may carry a TZID parameter.
_TZID_PROPS = frozenset(
    ["DTSTART", "DTEND", "DUE", "RECURRENCE-ID", "EXDATE", "RDATE", "DTDUE"]
)


def _translate(tzid: str) -> str:
    """Return the IANA name for *tzid*, or *tzid* unchanged if already IANA."""
    translated = WINDOWS_TO_IANA.get(tzid)
    if translated is None:
        logger.debug("TZID %r not in lookup table — leaving unchanged", tzid)
        return tzid
    if translated != tzid:
        logger.info("Translated TZID %r → %r", tzid, translated)
    return translated


def _collect_tzids(cal: Calendar) -> set[str]:
    """Walk the calendar tree and collect every TZID referenced anywhere."""
    tzids: set[str] = set()

    # From VTIMEZONE components
    for component in cal.walk("VTIMEZONE"):
        raw = component.get("TZID")
        if raw:
            tzids.add(str(raw))

    # From properties on event-like components
    for comp_name in ("VEVENT", "VTODO", "VJOURNAL"):
        for component in cal.walk(comp_name):
            for prop_name in _TZID_PROPS:
                prop = component.get(prop_name)
                if prop is None:
                    continue
                # A property can be a list (e.g. EXDATE)
                props = prop if isinstance(prop, list) else [prop]
                for p in props:
                    tzid = getattr(p, "params", {}).get("TZID")
                    if tzid:
                        tzids.add(str(tzid))

    return tzids


def _rewrite_tzid_params(cal: Calendar, translation: dict[str, str]) -> None:
    """Mutate *cal* in place: replace Windows TZID params with IANA names."""
    for comp_name in ("VEVENT", "VTODO", "VJOURNAL"):
        for component in cal.walk(comp_name):
            for prop_name in _TZID_PROPS:
                prop = component.get(prop_name)
                if prop is None:
                    continue
                props = prop if isinstance(prop, list) else [prop]
                for p in props:
                    params = getattr(p, "params", {})
                    old_tzid = params.get("TZID")
                    if old_tzid and old_tzid in translation:
                        params["TZID"] = translation[old_tzid]


def _replace_vtimezone_blocks(cal: Calendar, translation: dict[str, str]) -> None:
    """
    Remove all VTIMEZONE sub-components from *cal* and inject authoritative
    definitions (generated by icalendar.Timezone.from_tzid) for every
    translated IANA zone.

    Unknown/invalid IANA names are skipped with a warning.
    """
    # Remove existing VTIMEZONE blocks
    cal.subcomponents = [
        c for c in cal.subcomponents if c.name != "VTIMEZONE"
    ]

    injected: set[str] = set()
    for iana_name in sorted(set(translation.values())):
        if iana_name in injected:
            continue
        try:
            vtimezone = Timezone.from_tzid(iana_name)
        except Exception as exc:
            logger.warning(
                "Could not build VTIMEZONE for %r: %s — block omitted",
                iana_name,
                exc,
            )
            continue
        cal.add_component(vtimezone)
        injected.add(iana_name)
        logger.debug("Injected VTIMEZONE for %r", iana_name)


def rewrite_calendar(ics_bytes: bytes) -> bytes:
    """
    Parse *ics_bytes*, translate Windows timezone names, and return the
    rewritten calendar as bytes.
    """
    cal = Calendar.from_ical(ics_bytes)

    # Step 1: collect all TZID strings referenced in this calendar
    raw_tzids = _collect_tzids(cal)
    if not raw_tzids:
        logger.info("No TZID references found — returning feed unchanged")
        return cal.to_ical()

    # Step 2: build translation map (only for names that need changing)
    translation: dict[str, str] = {}
    for tzid in raw_tzids:
        iana = _translate(tzid)
        if iana != tzid:
            translation[tzid] = iana

    if not translation:
        logger.info("All TZIDs are already IANA names — returning feed unchanged")
        return cal.to_ical()

    # Step 3: rewrite TZID parameters on event properties
    _rewrite_tzid_params(cal, translation)

    # Step 4: replace VTIMEZONE blocks with authoritative definitions
    _replace_vtimezone_blocks(cal, translation)

    return cal.to_ical()


def fetch_and_rewrite(url: str, timeout: int = 30) -> bytes:
    """
    Fetch an ICS feed from *url* and return the timezone-rewritten bytes.

    Raises:
        requests.HTTPError: if the upstream server returns an error status.
        requests.Timeout: if the upstream server does not respond in time.
        ValueError: if the response body cannot be parsed as iCalendar data.
    """
    logger.info("Fetching upstream ICS: %s", url)
    response = requests.get(
        url,
        timeout=timeout,
        headers={"User-Agent": "outlook-ics-proxy/1.0 (+https://github.com/)"},
    )
    response.raise_for_status()

    try:
        return rewrite_calendar(response.content)
    except Exception as exc:
        raise ValueError(f"Failed to parse/rewrite ICS data from {url!r}: {exc}") from exc
